# Generated by Django 6.0.2 on 2026-09-22 09:29

import utils.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='aadhaar',
            field=utils.encrypted_fields.EncryptedCharField(blank=True, max_length=12, null=True),
        ),
    ]
