# Generated by Django 6.0.2 on 2026-06-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('updated_by', models.CharField(default='System', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaint.complaint')),
            ],
        ),
    ]
