# Generated by Django 6.0.2 on 2026-03-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('state_admin', 'State Admin'), ('citizen', 'Citizen')], max_length=20)),
            ],
        ),
    ]
