# Generated by Django 6.0.2 on 2026-06-22 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('village_officer', 'Village Officer'), ('taluka_officer', 'Taluka Officer'), ('district_officer', 'District Officer'), ('state_officer', 'State Officer'), ('super_admin', 'Super Admin')], default='citizen', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['district'], name='account_cit_distric_5b2637_idx'), models.Index(fields=['taluka'], name='account_cit_taluka_4dd61e_idx')],
            },
        ),
    ]
