# Generated by Django 6.0.2 on 2026-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('village_officer', 'Village Officer'), ('taluka_officer', 'Taluka Officer'), ('district_officer', 'District Officer'), ('state_officer', 'State Officer'), ('super_admin', 'Super Admin')], default='citizen', max_length=20),
        ),
    ]
