# Generated by Django 6.0.2 on 2026-03-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='taluka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
