# Generated by Django 6.0.2 on 2026-03-06 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('ward', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
