# Generated by Django 6.0.2 on 2026-06-20 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Agriculture', 'Agriculture'), ('Health', 'Health'), ('Housing', 'Housing'), ('Employment', 'Employment'), ('Social Welfare', 'Social Welfare'), ('Women & Child Welfare', 'Women & Child Welfare'), ('Infrastructure', 'Infrastructure'), ('General', 'General')], default='General', max_length=100)),
                ('level', models.CharField(choices=[('central', 'Central'), ('state', 'State'), ('district', 'District'), ('taluka', 'Taluka'), ('village', 'Village')], default='state', max_length=20)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('official_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='schemes/')),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
                'ordering': ['-created_at'],
            },
        ),
    ]
