# Generated by Django 6.0.2 on 2026-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_scheme_is_verified_scheme_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schemes/'),
        ),
    ]
