# Generated by Django 6.0.2 on 2026-09-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('update', 'Update'), ('alert', 'Alert'), ('scheme', 'Scheme')], default='announcement', max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category'], name='post_post_categor_f0b0d0_idx'),
        ),
    ]
