# Generated by Django 5.2.6 on 2026-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('EVENTS', 'Events'), ('OFFICE', 'Office'), ('CAMPAIGNS', 'Campaigns'), ('AWARDS', 'Awards & Certificates'), ('OTHER', 'Other')], default='EVENTS', max_length=12)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded'],
            },
        ),
    ]
