# Generated by Django 6.0.2 on 2026-03-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cricheroes_link', models.URLField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
