# Generated by Django 6.0.2 on 2026-03-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
