# Generated by Django 5.2.17 on 2026-09-24 03:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('ANNUAL', 'Annual report'), ('PERFORMANCE', 'Performance report'), ('AUDIT', 'Audit report'), ('SURVEY', 'Survey / study'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('summary', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('external_link', models.URLField(blank=True, help_text='Use this instead of a file for an external official link')),
                ('official_source', models.URLField(blank=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
