# Generated by Django 5.2.17 on 2026-09-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('official_source', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
