# Generated by Django 5.1.7 on 2026-08-25 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed, e.g. CREATE, UPDATE, DELETE, LOGIN, LOGOUT.', max_length=50)),
                ('model_name', models.CharField(help_text='Name of the model affected.', max_length=100)),
                ('object_id', models.CharField(help_text='Primary key of the affected object.', max_length=100)),
                ('changes', models.TextField(blank=True, default='', help_text='JSON-serialised dict of changes (field: old_value, new_value).')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address.', null=True)),
                ('user_agent', models.CharField(blank=True, default='', help_text='User agent string.', max_length=255)),
                ('request_path', models.CharField(blank=True, default='', help_text='The URL path of the request.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action was logged.')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx')],
            },
        ),
    ]
