# Generated by Django 5.2.17
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_coordinate_validators'),
        ('departments', '0002_department_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='departments.department'),
        ),
    ]
