# Generated by Django 5.2.17
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[
                ('ADMIN', 'Administration & Governance'),
                ('AGRI', 'Agriculture & Rural Development'),
                ('HEALTH', 'Health & Family Welfare'),
                ('EDU', 'Education & Skills'),
                ('LABOUR', 'Employment & Labour'),
                ('INDUSTRY', 'Industry & Economy'),
                ('URBAN', 'Housing & Urban Development'),
                ('ENV', 'Environment & Natural Resources'),
                ('SAFETY', 'Public Safety & Justice'),
                ('TRANSPORT', 'Transport'),
                ('WELFARE', 'Social Welfare'),
                ('CULTURE', 'Culture & Tourism'),
                ('OTHER', 'Other'),
            ], default='OTHER', max_length=12),
        ),
        migrations.AddField(
            model_name='department',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='One responsibility per line'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Head of Department'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod_designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Office phone'),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='website',
            field=models.URLField(blank=True, verbose_name='Official website'),
        ),
        migrations.AddField(
            model_name='department',
            name='citizen_helpline',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='department',
            name='grievance_officer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='department',
            name='grievance_portal_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='rti_officer',
            field=models.CharField(blank=True, max_length=150, verbose_name='Public Information Officer (RTI)'),
        ),
        migrations.AddField(
            model_name='department',
            name='rti_appellate_authority',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='department',
            name='source_url',
            field=models.URLField(blank=True, help_text='Official government page this profile is based on'),
        ),
        migrations.AddField(
            model_name='department',
            name='last_verified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.CharField(blank=True, help_text='Revenue division, e.g. Nashik Division', max_length=80),
        ),
        migrations.AddField(
            model_name='district',
            name='headquarters',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='district',
            name='area_sq_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='population_reference_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='talukas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='villages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='district',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='DepartmentOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Leave blank to show only the designation', max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('responsibility', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='departments.department')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
