# Generated by Django 6.0.2 on 2026-09-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, help_text='What this department does, in plain language'),
        ),
    ]
